#!/usr/bin/env python3
"""Generate a minimal OMSP-compliant repository structure safely."""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{1,62}$")


@dataclass(frozen=True)
class PlannedFile:
    path: str
    action: str
    content: str


def load_profile(path: Path) -> dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    required = ("repository_name", "title", "owner")
    missing = [key for key in required if not str(data.get(key, "")).strip()]
    if missing:
        raise ValueError(f"missing profile fields: {', '.join(missing)}")
    name = str(data["repository_name"])
    if not NAME_RE.fullmatch(name):
        raise ValueError("repository_name must be lowercase and filesystem-safe")
    return {key: str(value) for key, value in data.items()}


def render(profile: dict[str, str]) -> dict[str, str]:
    name = profile["repository_name"]
    title = profile["title"]
    owner = profile["owner"]
    artifact_prefix = profile.get("artifact_prefix", "OMSP-PROJECT").upper()
    readme = f"# {title}\n\nGenerated by OMSP Repository Generator MVP.\n"
    governance = f"""---
Artifact-ID: {artifact_prefix}-GOVERNANCE-0001
Title: {title} Governance
Version: 0.1.0
Status: Draft
Owner: {owner}
---

# {title} Governance

This generated artifact is a draft and requires accountable human review before becoming authoritative.
"""
    profile_json = json.dumps(profile, indent=2, sort_keys=True) + "\n"
    return {
        "README.md": readme,
        "governance/GOVERNANCE.md": governance,
        "planning/README.md": "# Planning\n\nGoverned planning artifacts belong here.\n",
        "validation/README.md": "# Validation\n\nValidation evidence and checklists belong here.\n",
        ".omsp/repository-profile.json": profile_json,
        ".gitignore": "build/\ndist/\n*.tmp\n",
    }


def plan(output: Path, files: dict[str, str], force: bool) -> list[PlannedFile]:
    result: list[PlannedFile] = []
    for relative, content in sorted(files.items()):
        destination = output / relative
        if destination.exists():
            if destination.is_dir():
                raise ValueError(f"destination is a directory: {relative}")
            current = destination.read_text(encoding="utf-8")
            if current == content:
                action = "unchanged"
            elif force:
                action = "overwrite"
            else:
                action = "blocked"
        else:
            action = "create"
        result.append(PlannedFile(relative, action, content))
    return result


def apply(output: Path, entries: list[PlannedFile]) -> None:
    blocked = [entry.path for entry in entries if entry.action == "blocked"]
    if blocked:
        raise ValueError("refusing to overwrite existing files: " + ", ".join(blocked))
    for entry in entries:
        if entry.action in {"create", "overwrite"}:
            destination = output / entry.path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(entry.content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("profile", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    try:
        profile = load_profile(args.profile)
        entries = plan(args.output, render(profile), args.force)
        if not args.dry_run:
            apply(args.output, entries)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    report = {
        "tool": {"name": "omsp-repository-generator", "version": "0.1.0"},
        "mode": "dry-run" if args.dry_run else "write",
        "output": str(args.output),
        "summary": {action: sum(e.action == action for e in entries) for action in ("create", "overwrite", "unchanged", "blocked")},
        "files": [{"path": e.path, "action": e.action} for e in entries],
        "authority": "generated-draft-only",
    }
    rendered = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.report:
        args.report.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 1 if any(e.action == "blocked" for e in entries) else 0


if __name__ == "__main__":
    raise SystemExit(main())
